apiVersion: opensearch.opster.io/v1
kind: OpensearchComponentTemplate
metadata:
  name: index-privilege-logs-component-template
  namespace: monitoring
spec:
  opensearchCluster:
    name: monitoring-cluster
  template:
    mappings:
      properties:
        missing_privileges:
          type: nested
        available_privileges:
          type: nested