apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: index-privilege-logs-index-template
  namespace: monitoring
spec:
  opensearchCluster:
    name: monitoring-cluster
  indexPatterns:
    - opensearch-missing-index-privileges-logs
  composedOf:
    - index-privilege-logs-component-template