apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: monitoring-cluster
  namespace: monitoring
spec:
  security:
    config:
      adminCredentialsSecret:
        name: admin-credentials-secret
      securityConfigSecret:
        name: security-config-secret
    tls:
      http:
        generate: true
      transport:
        generate: true
  general:
    httpPort: 9200
    serviceName: monitoring-cluster
    version: 2.19.1
    pluginsList: []
    drainDataNodes: true
    additionalConfig:
       path.logs: /usr/share/opensearch/logs/
       plugins.security.audit.type: log4j
       plugins.security.unsupported.restapi.allow_securityconfig_modification: "true"
       plugins.security.allow_default_init_securityindex: "true"
       plugins.security.allow_unsafe_democertificates: "true"
       plugins.security.ssl.transport.enforce_hostname_verification: "false"
       plugins.security.nodes_dn: "[\"*\"]"
       plugins.security.ssl.transport.enabled: "true"
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.19.1
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    opensearchCredentialsSecret:
      name: dashboards-credentials-secret
  nodePools:
    - component: masters
      replicas: 3
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        emptyDir: {}


