apiVersion: v1
kind: Secret
metadata:
  name: security-config-secret
  namespace: monitoring
type: Opaque
stringData:
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      backend_roles:
      - "admin"
    dashboards_server:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
    fluentbit:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - fluentbit
    dataprepper:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - dataprepper
  roles_mapping.yml: |-
    _meta:
      type: "rolesmapping"
      config_version: 2
    all_access:
      reserved: false
      backend_roles:
      - "admin"
    kibana_server:
      users:
      - "dashboards_server"
  roles.yml: |-
    _meta:
      type: "roles"
      config_version: 2
    fluentbit:
      cluster_permissions:
        - cluster_composite_ops
      index_permissions:
        - index_patterns:
          - opensearch-logs*
          - opensearch-missing-index-privileges-logs*
          allowed_actions:
          - crud
          - create_index
    dataprepper:
      cluster_permissions:
        - cluster_composite_ops
        - cluster_monitor
      index_permissions:
        - index_patterns:
          - opensearch-audit-logs
          allowed_actions:
          - crud
          - create_index
          - manage
        - index_patterns:
          - "*"
          allowed_actions:
          - indices:admin/aliases/get
  config.yml: |-
    _meta:
      type: "config"
      config_version: "2"
    config:
      dynamic:
        kibana:
          multitenancy_enabled: false    
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            order: 1
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern
  action_groups.yml:  |-
    _meta:
      type: "actiongroups"
      config_version: "2"
  allowlist.yml:  |-
    _meta:
      type: "allowlist"
      config_version: "2"
  whitelist.yml:  |-
    _meta:
      type: "whitelist"
      config_version: "2"
  audit.yml:  |-
    _meta:
      type: "audit"
      config_version: "2"
  nodes_dn.yml:  |-
    _meta:
      type: "nodesdn"
      config_version: "2"
  tenants.yml:  |-
    _meta:
      type: "tenants"
      config_version: "2"    
