apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-config
  namespace: default
data:
  log4j2.properties: |
    status = error

    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name][%X{user}]%marker %m%n

    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console