apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: main-cluster
  namespace: default
spec:
  security:
    config:
      adminCredentialsSecret:
        name: admin-credentials-secret
      securityConfigSecret:
        name: security-config-secret
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true
  general:
    httpPort: 9200
    serviceName: main-cluster
    version: 2.19.1
    pluginsList: []
    drainDataNodes: true
    additionalConfig:
      path.logs: /usr/share/opensearch/logs/
      plugins.security.audit.type: log4j
      plugins.security.unsupported.restapi.allow_securityconfig_modification: "true"
    additionalVolumes:
      - name: log4j2-config
        path: /usr/share/opensearch/config/log4j2.properties
        subPath: log4j2.properties
        configMap:
          name: log4j2-config
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.19.1
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    opensearchCredentialsSecret:
      name: dashboards-credentials-secret
  nodePools:
    - component: masters
      replicas: 3
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        emptyDir: {}