apiVersion: v1
kind: Secret
metadata:
  name: security-config-secret
type: Opaque
stringData:
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      backend_roles:
      - "admin"
    dashboards_server:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
    broken_dls:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - broken_role_dls
      - kibana_user    
    broken_pattern:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - broken_role_index_pattern
      - kibana_user
    nils:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - kibana_user
      - broken_role
  roles_mapping.yml: |-
    _meta:
      type: "rolesmapping"
      config_version: 2
    all_access:
      backend_roles:
      - "admin"
    kibana_server:
      users:
      - "dashboards_server"
  roles.yml: |-
    _meta:
      type: "roles"
      config_version: 2
    broken_role_dls:
      cluster_permissions:
        - cluster_composite_ops_ro
      index_permissions:
        - index_patterns:
          - test_a*
          allowed_actions:
          - read
          - indices_monitor
          dls: "{\"term\": { \"public: ${user.name}}}"
    broken_role_index_pattern:
      cluster_permissions:
        - "indices:data/read/mget"
      index_permissions:
        - index_patterns:
          - "/test_${foo}/"
          allowed_actions:
          - "indices:data/read/search"
  config.yml: |-
    _meta:
      type: "config"
      config_version: "2"
    config:
      dynamic:
        kibana:
          multitenancy_enabled: false
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            order: 1
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern
  action_groups.yml:  |-
    _meta:
      type: "actiongroups"
      config_version: "2"
  allowlist.yml:  |-
    _meta:
      type: "allowlist"
      config_version: "2"
  whitelist.yml:  |-
    _meta:
      type: "whitelist"
      config_version: "2"
  audit.yml:  |-
    _meta:
      type: "audit"
      config_version: "2"
    config:
      enabled: true
      audit:
        disabled_rest_categories:
          - GRANTED_PRIVILEGES
        disabled_transport_categories:
          - GRANTED_PRIVILEGES
        ignore_users: 
          - kibanaserver    
      compliance:
        enabled: true
        internal_config: true
        write_metadata_only: false
        write_log_diffs: true
        write_watched_indices: [".opendistro_security"]
  nodes_dn.yml:  |-
    _meta:
      type: "nodesdn"
      config_version: "2"
  tenants.yml:  |-
    _meta:
      type: "tenants"
      config_version: "2"    
