apiVersion: v1
kind: Secret
metadata:
  name: security-config-secret
type: Opaque
stringData:
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      backend_roles:
      - "admin"
    dashboards_server:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
    broken:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - broken_role
    nils:
      hash: "$2y$12$XQD3cAdcnbbp5/damA6HwO1hdyDf.lN4H/71y.U5u8iWvUqGSr/5u"
      opendistro_security_roles:
      - kibana_user
      - broken_role
  roles_mapping.yml: |-
    _meta:
      type: "rolesmapping"
      config_version: 2
    all_access:
      backend_roles:
      - "admin"
    kibana_server:
      users:
      - "dashboards_server"
  roles.yml: |-
    _meta:
      type: "roles"
      config_version: 2
    broken_role:
      cluster_permissions:
        - "indices:data/read/mget"
      index_permissions:
        - index_patterns:
          - test_a*
          allowed_actions:
          - "indices:data/read/search"
  config.yml: |-
    _meta:
      type: "config"
      config_version: "2"
    config:
      dynamic:
        kibana:
          multitenancy_enabled: false
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            order: 1
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern